#!/usr/bin/env python3
"""sdc_generator.py — 综合保护机制。

为加固后的 RTL 代码添加综合保护属性，防止综合工具优化掉冗余的加固逻辑。

提供:
  - add_keep_attributes() — 为信号添加 (* keep = "true" *) 属性
  - generate_sdc_constraints() — 生成 SDC 约束文件
  - add_dont_touch_comments() — 添加 set_dont_touch 注释
"""

import re
from typing import Dict, List, Optional


def add_keep_attributes(
    rtl_content: str,
    signals_to_protect: List[str],
    modules_to_protect: List[str] = None
) -> str:
    """为指定信号添加 (* keep = "true" *) 属性。

    Args:
        rtl_content: 原始 RTL 源代码。
        signals_to_protect: 需要保护的信号列表。
        modules_to_protect: 需要保护的模块列表。

    Returns:
        添加保护属性后的 RTL 代码。
    """
    if modules_to_protect is None:
        modules_to_protect = []

    result = rtl_content
    lines = result.split('\n')
    new_lines = []

    for line in lines:
        modified = False

        for sig_name in signals_to_protect:
            patterns = [
                rf'(reg|wire|logic)\s+(?:\[.*?\])?\s+({re.escape(sig_name)})\s*[;,]',
                rf'(input|output|inout)\s+(?:wire|reg|logic)?\s*(?:\[.*?\])?\s+({re.escape(sig_name)})\s*[;,]',
            ]
            for pattern in patterns:
                match = re.search(pattern, line)
                if match:
                    prefix = match.group(1)
                    name = match.group(2)
                    if f'(* keep = "true" *)' not in line:
                        line = line.replace(
                            f'{prefix} {name}',
                            f'{prefix} (* keep = "true" *) {name}',
                            1
                        )
                        modified = True
                        break

        for mod_name in modules_to_protect:
            match = re.search(rf'(module|endmodule)\s+({re.escape(mod_name)})', line)
            if match and f'(* keep_hierarchy = "yes" *)' not in line:
                if match.group(1) == 'module':
                    line = line.replace(
                        f'module {mod_name}',
                        f'(* keep_hierarchy = "yes" *) module {mod_name}',
                        1
                    )
                    modified = True

        new_lines.append(line)

    return '\n'.join(new_lines)


def generate_sdc_constraints(
    module_name: str,
    protected_signals: List[str],
    protected_modules: List[str] = None,
    output_path: Optional[str] = None
) -> str:
    """生成 SDC 约束文件，防止综合工具优化掉加固逻辑。

    Args:
        module_name: 顶层模块名。
        protected_signals: 需要保护的信号列表。
        protected_modules: 需要保护的模块列表。
        output_path: 输出文件路径（可选）。

    Returns:
        SDC 约束内容。
    """
    if protected_modules is None:
        protected_modules = []

    sdc_lines = [
        f'# SDC Constraints for {module_name} Hardened Design',
        f'# Generated by sdc_generator.py',
        f'# Protect TMR/DICE/ECC logic from synthesis optimization',
        '',
    ]

    sdc_lines.append('# =======================================================')
    sdc_lines.append('# Module-level protection')
    sdc_lines.append('# =======================================================')
    for mod_name in protected_modules:
        sdc_lines.append(f'set_dont_touch [get_cells *{mod_name}*]')
        sdc_lines.append(f'set_keep_hierarchy [get_cells *{mod_name}*]')
    sdc_lines.append('')

    sdc_lines.append('# =======================================================')
    sdc_lines.append('# Signal-level protection')
    sdc_lines.append('# =======================================================')
    for sig_name in protected_signals:
        sdc_lines.append(f'set_dont_touch [get_nets *{sig_name}*]')
    sdc_lines.append('')

    sdc_lines.append('# =======================================================')
    sdc_lines.append('# TMR-specific protection')
    sdc_lines.append('# =======================================================')
    sdc_lines.append('# Protect voter instances')
    sdc_lines.append('set_dont_touch [get_cells *voter*]')
    sdc_lines.append('set_dont_touch [get_cells *majority*]')
    sdc_lines.append('')

    sdc_lines.append('# Protect TMR replicated signals')
    sdc_lines.append('set_dont_touch [get_nets *tmr_error*]')
    sdc_lines.append('set_dont_touch [get_nets *A]')
    sdc_lines.append('set_dont_touch [get_nets *B]')
    sdc_lines.append('set_dont_touch [get_nets *C]')
    sdc_lines.append('')

    sdc_lines.append('# =======================================================')
    sdc_lines.append('# DICE-specific protection')
    sdc_lines.append('# =======================================================')
    sdc_lines.append('set_dont_touch [get_cells *dice*]')
    sdc_lines.append('set_dont_touch [get_nets *n1*]')
    sdc_lines.append('set_dont_touch [get_nets *n2*]')
    sdc_lines.append('set_dont_touch [get_nets *p1*]')
    sdc_lines.append('set_dont_touch [get_nets *p2*]')
    sdc_lines.append('')

    sdc_lines.append('# =======================================================')
    sdc_lines.append('# ECC-specific protection')
    sdc_lines.append('# =======================================================')
    sdc_lines.append('set_dont_touch [get_cells *ecc*]')
    sdc_lines.append('set_dont_touch [get_cells *encoder*]')
    sdc_lines.append('set_dont_touch [get_cells *decoder*]')
    sdc_lines.append('')

    sdc_lines.append('# =======================================================')
    sdc_lines.append('# General synthesis constraints')
    sdc_lines.append('# =======================================================')
    sdc_lines.append('# Prevent retiming of hardened registers')
    sdc_lines.append('set_fix_multiple_port_nets -all -buffer_constants')
    sdc_lines.append('')

    sdc_content = '\n'.join(sdc_lines)

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(sdc_content)

    return sdc_content


def add_dont_touch_comments(
    rtl_content: str,
    signals_to_protect: List[str]
) -> str:
    """在 RTL 代码中添加 set_dont_touch 注释。

    Args:
        rtl_content: 原始 RTL 源代码。
        signals_to_protect: 需要保护的信号列表。

    Returns:
        添加保护注释后的 RTL 代码。
    """
    result = rtl_content

    for sig_name in signals_to_protect:
        result = result.replace(
            f'reg {sig_name}',
            f'reg /* synthesis set_dont_touch */ {sig_name}'
        )
        result = result.replace(
            f'wire {sig_name}',
            f'wire /* synthesis set_dont_touch */ {sig_name}'
        )

    return result


def generate_protected_rtl(
    rtl_content: str,
    strategy_map: Dict[str, str],
    module_name: str = 'top',
    sdc_output_path: Optional[str] = None
) -> str:
    """生成完整的受保护 RTL 代码。

    Args:
        rtl_content: 原始 RTL 源代码。
        strategy_map: 策略映射 {signal: strategy}。
        module_name: 模块名。
        sdc_output_path: SDC 文件输出路径（可选）。

    Returns:
        添加保护属性后的 RTL 代码。
    """
    protected_signals = list(strategy_map.keys())
    protected_modules = []

    result = add_keep_attributes(rtl_content, protected_signals, protected_modules)
    result = add_dont_touch_comments(result, protected_signals)

    if sdc_output_path:
        generate_sdc_constraints(
            module_name,
            protected_signals,
            protected_modules,
            sdc_output_path
        )

    return result


def protect_tmr_logic(rtl_content: str) -> str:
    """自动识别并保护 TMR 相关逻辑。

    Args:
        rtl_content: 原始 RTL 源代码。

    Returns:
        添加保护属性后的 RTL 代码。
    """
    tmr_patterns = [
        r'_A\b', r'_B\b', r'_C\b',
        r'tmr_error',
        r'majority',
        r'voter',
    ]

    protected_signals = []
    for pattern in tmr_patterns:
        matches = re.findall(pattern, rtl_content)
        protected_signals.extend(matches)

    protected_signals = list(set(protected_signals))
    return add_keep_attributes(rtl_content, protected_signals)


def protect_dice_logic(rtl_content: str) -> str:
    """自动识别并保护 DICE 相关逻辑。

    Args:
        rtl_content: 原始 RTL 源代码。

    Returns:
        添加保护属性后的 RTL 代码。
    """
    dice_patterns = [
        r'\bn1\b', r'\bn2\b', r'\bp1\b', r'\bp2\b',
        r'dice',
    ]

    protected_signals = []
    for pattern in dice_patterns:
        matches = re.findall(pattern, rtl_content)
        protected_signals.extend(matches)

    protected_signals = list(set(protected_signals))
    return add_keep_attributes(rtl_content, protected_signals)


def protect_ecc_logic(rtl_content: str) -> str:
    """自动识别并保护 ECC 相关逻辑。

    Args:
        rtl_content: 原始 RTL 源代码。

    Returns:
        添加保护属性后的 RTL 代码。
    """
    ecc_patterns = [
        r'ecc',
        r'encoder',
        r'decoder',
        r'parity',
        r'syndrome',
    ]

    protected_signals = []
    for pattern in ecc_patterns:
        matches = re.findall(pattern, rtl_content, re.IGNORECASE)
        protected_signals.extend(matches)

    protected_signals = list(set(protected_signals))
    return add_keep_attributes(rtl_content, protected_signals)